# Generated by Django 5.1.4 on 2024-12-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateblood',
            name='date_of_birth',
            field=models.PositiveIntegerField(),
        ),
    ]
