# Generated by Django 5.1.4 on 2025-06-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateblood',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestblood',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
