# Generated by Django 5.1.4 on 2024-12-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_alter_donateblood_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateblood',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
